# Generated by Django 6.0.2 on 2026-04-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_chat_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='FinalTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('route', models.JSONField(blank=True, default=list)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_markdown', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_trip', to='llm.chatthread')),
            ],
        ),
    ]
