# Generated by Django 6.0.2 on 2026-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_chatthread_is_archived_finaltrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltrip',
            name='daily_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finaltrip',
            name='travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finaltrip',
            name='trip_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
