# Generated by Django 6.0.2 on 2026-04-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_finaltrip_daily_budget_finaltrip_travelers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltrip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finaltrip',
            name='safety_tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finaltrip',
            name='sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='finaltrip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
