# Generated by Django 6.0.2 on 2026-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_finaltrip_end_date_finaltrip_safety_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltrip',
            name='trip_length',
            field=models.IntegerField(blank=True, help_text='Duration of trip in days', null=True),
        ),
    ]
