# Generated by Django 6.0.2 on 2026-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_add_trip_length_to_finaltrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='auto_title',
            field=models.BooleanField(default=True),
        ),
    ]
