# Generated by Django 6.0.2 on 2026-03-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_comment'),
        ('places', '0016_merge_20260226_1853'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='marketplace_trip_id_3008a2_idx',
        ),
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['place', 'created_at'], name='marketplace_place_i_662fcd_idx'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='trip',
        ),
    ]
