# Generated by Django 6.0.2 on 2026-03-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tripmedia'),
        ('marketplace', '0003_remove_comment_marketplace_trip_id_3008a2_idx_and_more'),
    ]

    operations = [
    ]
