# Generated by Django 6.0.2 on 2026-04-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_comment_likes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='marketplace_place_i_78595c_idx',
            old_name='marketplace_comment_pop_idx',
        ),
        migrations.RenameIndex(
            model_name='commentlike',
            new_name='marketplace_comment_d839f1_idx',
            old_name='marketplace_cl_comment_crt_idx',
        ),
    ]
