# Generated by Django 5.0.3 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='open_now',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
