# Generated by Django 5.0.3 on 2026-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cover'),
        ('users', '0003_user_deleted_at'),
    ]

    operations = [
    ]
