# Generated by Django 6.0.2 on 2026-02-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cover'),
        ('users', '0003_user_deleted_at'),
    ]

    operations = [
    ]
