# Generated by Django 6.0.2 on 2026-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0003_user_cover_0003_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('TRIPADVISOR', 'TripAdvisor'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], db_index=True, default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_level',
            field=models.CharField(default='BRONZE', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
