# Generated by Django 6.0.2 on 2026-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_block_expires_at_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='share_badges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='share_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='share_visited_places',
            field=models.BooleanField(default=False),
        ),
    ]
