# Generated by Django 5.0.3 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='restaurant, museum, attraction', max_length=50)),
                ('types', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'category'], name='places_plac_city_028228_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('city', 'category')},
            },
        ),
    ]
