# Generated by Django 5.0.3 on 2026-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_saves_count_place_status_alter_place_cached_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='Japan', max_length=100),
            preserve_default=False,
        ),
    ]
