# Generated by Django 5.0.3 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='is_must_visit',
            field=models.BooleanField(default=False),
        ),
    ]
