# Generated by Django 5.0.3 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_add_place_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
