# Generated by Django 5.0.3 on 2026-02-08 00:00

from django.db import migrations, models


def seed_interest_mappings(apps, schema_editor):
    InterestMapping = apps.get_model('places', 'InterestMapping')

    defaults = {
        "cute museums": ["museum", "art_gallery"],
        "culture": ["museum", "historical", "temple"],
        "food": ["restaurant", "cafe"],
        "coffee": ["cafe"],
        "cafes": ["cafe"],
        "nightlife": ["bar", "night_club"],
        "nature": ["park", "natural_feature"],
        "shopping": ["shopping_mall", "clothing_store", "market"],
        "history": ["museum", "historical", "monument", "tourist_attraction"],
        "art": ["art_gallery", "museum"],
        "views": ["tourist_attraction", "viewpoint"],
        "family": ["zoo", "aquarium", "park", "amusement_park"],
    }

    for name, google_types in defaults.items():
        InterestMapping.objects.update_or_create(
            name=name,
            defaults={"mappings": {"google": google_types}},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_expand_place_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mappings', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RunPython(seed_interest_mappings, migrations.RunPython.noop),
    ]
