# Generated by Django 5.0.3 on 2026-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_expand_place_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
