# Generated by Django 5.0.3 on 2026-02-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_interest_mapping'),
        ('places', '0009_remove_savedplace_tour_fields'),
    ]

    operations = [
    ]
