<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-19 11:24
=======
# Generated by Django 6.0.2 on 2026-02-20 19:38
>>>>>>> 69ffdbe91d0e4163619203e09035e8e299cdf34a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_add_visited_at'),
        ('places', '0010_merge_20260212_1946'),
    ]

    operations = [
    ]
