# Generated by Django 6.0.2 on 2026-02-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_add_visited_at'),
        ('places', '0010_merge_20260212_1946'),
    ]

    operations = [
    ]
