# Generated by Django 5.0.3 on 2026-02-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_add_visited_at'),
        ('places', '0012_usermapplace'),
    ]

    operations = [
    ]
