# Generated by Django 5.0.3 on 2026-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_merge_0010_add_visited_at_0012_usermapplace'),
    ]

    operations = [
    ]
