# Generated by Django 6.0.2 on 2026-02-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_merge_0010_add_visited_at_0012_usermapplace'),
    ]

    operations = [
    ]
