# Generated by Django 6.0.2 on 2026-02-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_merge_20260220_1904'),
        ('places', '0014_merge_20260221_0536'),
    ]

    operations = [
    ]
