# Generated by Django 5.0.3 on 2026-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_merge_20260220_1904'),
        ('places', '0014_merge_20260221_0536'),
    ]

    operations = [
    ]
