# Generated by Django 6.0.2 on 2026-02-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_merge_20260221_1012'),
        ('places', '0015_merge_20260224_2039'),
    ]

    operations = [
    ]
