# Generated by Django 6.0.2 on 2026-04-15 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_merge_20260226_1853'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tripadvisor', 'TripAdvisor'), ('ticketmaster', 'Ticketmaster')], db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_level', models.CharField(blank=True, max_length=30, null=True)),
                ('booking_url', models.URLField(blank=True, default='', max_length=1000)),
                ('web_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.CharField(blank=True, default='', max_length=120)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=120)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_external_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source', 'external_id')},
            },
        ),
    ]
