# Generated by Django 6.0.2 on 2026-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_externalsavedplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('ticketmaster', 'Ticketmaster')], default='ticketmaster', max_length=32)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=120)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, default='USD', max_length=16)),
                ('photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('web_url', models.URLField(blank=True, default='', max_length=1000)),
                ('booking_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.CharField(blank=True, default='', max_length=120)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'source'], name='places_cach_city_67568c_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('tripadvisor', 'TripAdvisor')], default='tripadvisor', max_length=32)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('subcategory', models.CharField(blank=True, default='', max_length=120)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, default='USD', max_length=16)),
                ('photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('web_url', models.URLField(blank=True, default='', max_length=1000)),
                ('booking_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.CharField(blank=True, default='', max_length=120)),
                ('award', models.JSONField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'source'], name='places_cach_city_e42964_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='CacheMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('source', models.CharField(choices=[('tripadvisor', 'TripAdvisor'), ('ticketmaster', 'Ticketmaster')], db_index=True, max_length=32)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('has_data', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('city', 'source')},
            },
        ),
    ]
