# Generated by Django 6.0.2 on 2026-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_cachedevent_cachedtour_cachemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedevent',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
